Update utils.py
Modif done because of this bug : 

```
abyss ~ # python
Python 3.6.4 (default, Feb  6 2018, 18:33:58)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pySMART import DeviceList
>>> devlist = DeviceList()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/lib64/python3.6/site-packages/pySMART/device_list.py", line 52, in __init__
    self._initialize()
  File "/root/.local/lib64/python3.6/site-packages/pySMART/device_list.py", line 98, in _initialize
    for line in _stdout.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```